services:
  # A web service
  - type: web
    name: accounting-educational-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: APP_URL
        sync: false
    autoDeploy: true